project:
  type: website

website:
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with Quarto"
  navbar:
    right:
      - text: About
        href: about/index.qmd
    left:
      - text: 1-800 Data Engineer
        href: index.qmd
      
format:
  html:
    theme: [cosmo, styles.scss]

